name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      
      - name: Install Node.js
      
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        run: |
          # Use Terraform to apply changes to infrastructure
          terraform init
          terraform apply -auto-approve
